//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgenciaAutomotiva
{
    using System;
    using System.Collections.Generic;
    
    public partial class Veiculos
    {
        public int id { get; set; }
        public string marca { get; set; }
        public string modelo { get; set; }
        public int ano { get; set; }
        public string cor { get; set; }
        public System.DateTime fabricacao { get; set; }
        public string combustivel { get; set; }
        public bool automatico { get; set; }
        public decimal valor { get; set; }
        public bool ativo { get; set; }
    }
}
